@UrlShortener_HostAddress = http://localhost:5173

# Create shortened url - input string is not a valid url
POST {{UrlShortener_HostAddress}}/shortenurl
Accept: application/json

{
    "url": "test",
}

###
